### ISSUE TITLE
airplace fully bypasses

### ISSUE THREAD

**Issue by feliscatusmeows** [CoolMineman/CheaterDeleter#15]
**Cheat Description**
it places blocks without a supporting block to placec on, aka places blocks in mid air

**Screenshot/Video**

**Link to Cheat**
airplace is present in https://bleachhack.github.io/ and https://meteorclient.com/

**Comment by feliscatusmeows** [comment]
fixed in `db0b181` :DDDDDDDDD

**Comment by CoolMineman** [comment]
patched
