### ISSUE TITLE
Problem with glide in water.

### ISSUE THREAD

**Issue by Trirez** [CoolMineman/CheaterDeleter#2]
When glide is enabled and the player goes in the water also it kicks out the player. 
But when the same player relogins with any hacks or just a legit client it kicks out instant.
Just float in water and the problem occurs repeatedly.
Log: 
[log.txt](https://github.com/CoolMineman/CheaterDeleter/files/6017267/log.txt)

**Comment by Trirez** [comment]
But its a great anti cheat mod and waiting for it.
Good Luck.
Always Testing.

**Comment by CoolMineman** [comment]
If that didn't fix it send a video or something this is not expected behavior from the Phase check

**Comment by Trirez** [comment]
Sure, I will test the changes once I return to my home.

**Comment by Trirez** [comment]
Nope, the fix didn't work.
Although creating new world might fix the issue.
There is small delay with elytraflight and when I was flying with only rockets, the mod flagged the player for speed.
[Compile changelog.txt](https://github.com/CoolMineman/CheaterDeleter/files/6017466/Compile.changelog.txt)
[New world log.txt](https://github.com/CoolMineman/CheaterDeleter/files/6017467/New.world.log.txt)
[After commit change.log](https://github.com/CoolMineman/CheaterDeleter/files/6017468/After.commit.change.log)

Video Proof:
https://filebin.net/z5vnxvrj6iisa2el ( contains 1st video After commit fix. 2nd video New world.)

**Comment by CoolMineman** [comment]
That speed false flag is actually vanilla's anti-cheat.
